### PR TITLE
bug ng-packagr

### PR DESCRIPTION
**Pull request by splincode**
```
$ export DEBUG=true && yarn build:lib
yarn run v1.21.1
$ ts-node --project tools/tsconfig.tools.json tools/build && ts-node --project tools/tsconfig.tools.json tools/copy-readme
Building Angular Package
[debug] Found primary entry point: @ngxs-labs/data
WARNING: Cannot read secondary entry point at D:/Develop/data/lib/common. Skipping.
WARNING: Cannot read secondary entry point at D:/Develop/data/lib/internals. Skipping.
WARNING: Cannot read secondary entry point at D:/Develop/data/lib/utils. Skipping.
[debug] rimraf D:\Develop\data\dist\ngxs-data
[debug] Initializing tsconfig for @ngxs-labs/data
[debug] Analysing sources for @ngxs-labs/data
[debug] tsc program structure is reused: No old program
ERROR: Entry point @ngxs-labs/data/common which is required by @ngxs-labs/data doesn't exists.
Error: Entry point @ngxs-labs/data/common which is required by @ngxs-labs/data doesn't exists.
    at analyseEntryPoint (D:\Develop\data\node_modules\src\lib\ng-package\entry-point\analyse-sources.transform.ts:122:13)
    at MapSubscriber.project (D:\Develop\data\node_modules\src\lib\ng-package\entry-point\analyse-sources.transform.ts:17:7)
    at MapSubscriber._next (D:\Develop\data\node_modules\rxjs\src\internal\operators\map.ts:84:29)
    at MapSubscriber.Subscriber.next (D:\Develop\data\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (D:\Develop\data\node_modules\rxjs\src\internal\operators\switchMap.ts:172:24)
    at InnerSubscriber._next (D:\Develop\data\node_modules\rxjs\src\internal\InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (D:\Develop\data\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at MapSubscriber._next (D:\Develop\data\node_modules\rxjs\src\internal\operators\map.ts:89:22)
    at MapSubscriber.Subscriber.next (D:\Develop\data\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at D:\Develop\data\node_modules\rxjs\src\internal\util\subscribeToPromise.ts:8:20

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### CODE REVIEW

**Comment by alan-agius4** [comment]
The problem is that `flatModuleFile` is not a valid property. `flatModuleFile` is a child property of `lib`. Note: that in most cases, you shouldn't be setting this property as it is auto set,

**Comment by splincode** [comment]
@alan-agius4 thank you :) it would be great if in debug mode it would be written which configs are used by the modules during compilation, I didn’t think at all that I did something wrong

https://github.com/ngxs-labs/data/blob/master/lib/internals/src/public_api.ts

However, what problem am I trying to solve? If you uncomment this line of code, the library will stop compiling

configs (subpackage.json) do not change as in this PR

**Comment by splincode** [comment]
see: https://github.com/ngxs-labs/data/pull/202/files

**Comment by splincode** [comment]
Build success but

$ ts-node --project tools/tsconfig.tools.json tools/build && ts-node --project tools/tsconfig.tools.json tools/copy-readme
Building Angular Package
------------------------------------------------------------------------------

empty, why?

**Comment by alan-agius4** [comment]
The problem is that you are creating a circular dependency which is not allowed. That said, we should emit an error when such thing happens

**Pull request closed without merging**
